matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      sudo: false
      cache:
        yarn: true
        directories:
        - node_modules
      script:
        - yarn install
        - yarn test
        - yarn run build
    - language: python
      python:
        - "3.7"
      sudo: false
      script:
        - pip install -r requirements.txt
        - pip install -r dev-requirements.txt
        - py.test tests
