matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      sudo: false
      cache:
        yarn: true
        directories:
        - node_modules
      script:
        - yarn install
        - yarn test
        - yarn run build
      deploy:
        provider: script
        skip_cleanup: true
        script: APP_TAG=dash bash scripts/deploy
        on:
          tags: true
    - language: python
      dist: xenial
      python:
        - "3.7"
      sudo: false
      install:
        - pip install -r requirements.txt
        - pip install -r dev-requirements.txt
      script:
        - py.test tests
      services:
        - docker
      deploy:
        provider: script
        skip_cleanup: true
        script: APP_TAG=api bash scripts/deploy
        on:
          tags: true
