#!/bin/bash

set -e

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker build -f ./dockerfiles/api.dockerfile -t $DOCKER_IMAGE_NAME:latest .;

if [ ! -z "$TRAVIS_TAG" ]; then
    docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
fi && docker push $DOCKER_IMAGE_NAME
